import type { EvidenceUnit, Literature } from './types';

export const literature: Literature[] = [
  {
    id: 'RCT-01',
    title: '补阳还五汤治疗缺血性卒中恢复期气虚痰瘀证的随机对照研究',
    journal: '中国中西医结合杂志',
    year: '2024',
    tags: ['恢复期', '气虚痰瘀证', '益气活血', '补阳还五汤', 'NIHSS', 'RCT'],
    abstract: '观察组NIHSS评分较对照组降低3.2分，Barthel指数提高18分。',
  },
  {
    id: 'RCT-02',
    title: '脑心通胶囊对缺血性脑卒中气虚血瘀证患者的随机对照研究',
    journal: '中华中医药杂志',
    year: '2023',
    tags: ['恢复期', '气虚血瘀证', '活血通络', '脑心通胶囊', '证候积分', 'RCT'],
    abstract: '中医证候积分下降幅度优于对照组，血浆黏度降低。',
  },
  {
    id: 'SysRev-03',
    title: '醒脑开窍针法治疗缺血性卒中恢复期疗效的Meta分析',
    journal: '中国针灸',
    year: '2025',
    tags: ['恢复期', '气虚痰瘀证', '醒脑开窍针法', '总有效率', '系统综述'],
    abstract: '针法组总有效率提高，OR=2.34，95%CI 1.52-3.20。',
  },
  {
    id: 'OBS-04',
    title: '化痰通络汤对风痰阻络证脑卒中患者运动功能的前瞻性队列研究',
    journal: '中医脑病杂志',
    year: '2024',
    tags: ['恢复期', '风痰阻络证', '化痰通络', 'Fugl-Meyer', '队列研究'],
    abstract: '6个月随访显示Fugl-Meyer评分提高15.2分，mRS 0-2分比例达到42%。',
  },
];

export const initialEvidence: EvidenceUnit[] = [
  {
    id: 'RCT-01',
    title: literature[0].title,
    journal: '中国中西医结合杂志 · 2024',
    syndrome: '气虚痰瘀证',
    therapy: '益气活血',
    intervention: '补阳还五汤加减 + 常规治疗',
    formula: '补阳还五汤',
    outcome: 'NIHSS ↓3.2分；Barthel ↑18分',
    studyType: 'RCT',
    sourceText: '观察组NIHSS评分较对照组降低3.2分，Barthel指数提高18分，差异具有统计学意义。',
  },
  {
    id: 'RCT-02',
    title: literature[1].title,
    journal: '中华中医药杂志 · 2023',
    syndrome: '气虚血瘀证',
    therapy: '活血通络',
    intervention: '脑心通胶囊 + 基础治疗',
    formula: '脑心通胶囊',
    outcome: '中医证候积分 ↓6.2；血浆黏度 ↓15%',
    studyType: 'RCT',
    sourceText: '治疗后中医证候积分下降幅度优于对照组，血浆黏度较基线降低15.3%。',
  },
  {
    id: 'SysRev-03',
    title: literature[2].title,
    journal: '中国针灸 · 2025',
    syndrome: '气虚痰瘀证',
    therapy: '醒脑开窍',
    intervention: '醒脑开窍针法',
    formula: '针刺方案',
    outcome: '总有效率 OR=2.34 (95%CI 1.52-3.20)',
    studyType: '系统综述',
    sourceText: 'Meta分析显示针法组总有效率提高，OR=2.34，95%CI 1.52-3.20。',
  },
  {
    id: 'OBS-04',
    title: literature[3].title,
    journal: '中医脑病杂志 · 2024',
    syndrome: '风痰阻络证',
    therapy: '化痰通络',
    intervention: '化痰通络汤 + 康复训练',
    formula: '化痰通络汤',
    outcome: 'Fugl-Meyer ↑15.2；mRS改善率42%',
    studyType: '队列研究',
    sourceText: '6个月随访显示Fugl-Meyer评分提高15.2分，mRS 0-2分比例42%。',
  },
];
